# Generated by Django 6.0.6 on 2026-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('p1_emergency', 'P1 - Emergency'), ('p2_urgent', 'P2 - Urgent'), ('p3_routine', 'P3 - Routine'), ('p4_low', 'P4 - Low')], max_length=20, unique=True)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SLA policy',
                'verbose_name_plural': 'SLA policies',
                'ordering': ['priority'],
            },
        ),
    ]
